name: flutter_lib
description: nothing

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #Language
  intl: ^0.17.0

  #riverpod
  provider: ^6.0.2
  flutter_riverpod: ^1.0.3
  hooks_riverpod: ^1.0.3

  #UI
  sliding_up_panel: ^2.0.0+1
  dots_indicator: ^2.0.0
  readmore: ^2.1.0
  carousel_slider: ^4.0.0
  pin_code_fields: ^7.2.0
  pull_to_refresh: ^2.0.0
  email_validator: ^2.0.1
  animations: ^2.0.2
  simple_animations: ^4.0.1
  page_transition: ^2.0.4
  flutter_svg: ^1.0.3

  #Data local
  hive_flutter: ^1.0.0

  #File
  path_provider: ^2.0.1

  #Http, Json format
  json_serializable: ^6.1.3
  json_annotation: ^4.4.0

  #Google
  google_fonts: ^2.3.1

  #Other
  get_it: ^7.2.0
  tuple: ^2.0.0
  freezed: ^1.1.0
  freezed_annotation: ^1.1.0
  connectivity_plus: ^2.2.1

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  retrofit_generator: ^2.0.0+1
  hive_generator: ^1.1.0

flutter:

  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/